# Generated by Django 5.2.4 on 2025-08-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "⭐ - Poor"),
                    (2, "⭐⭐ - Fair"),
                    (3, "⭐⭐⭐ - Good"),
                    (4, "⭐⭐⭐⭐ - Very Good"),
                    (5, "⭐⭐⭐⭐⭐ - Excellent"),
                ],
                null=True,
            ),
        ),
    ]
